CREATE CONSTRAINT mapping_id IF NOT EXISTS FOR (m:MetaphorMapping) REQUIRE m.id IS UNIQUE;
CREATE CONSTRAINT frame_id IF NOT EXISTS FOR (f:MetaphorFrame) REQUIRE f.id IS UNIQUE;
CREATE CONSTRAINT cascade_id IF NOT EXISTS FOR (c:MetaphorCascade) REQUIRE c.id IS UNIQUE;
CREATE CONSTRAINT domain_name IF NOT EXISTS FOR (d:Domain) REQUIRE d.name IS UNIQUE;
CREATE CONSTRAINT chunk_id IF NOT EXISTS FOR (ch:Chunk) REQUIRE ch.id IS UNIQUE;
CREATE INDEX mapping_layer IF NOT EXISTS FOR (m:MetaphorMapping) ON (m.layer);
CREATE INDEX mapping_extended IF NOT EXISTS FOR (m:MetaphorMapping) ON (m.isExtended);
MERGE (d:Domain {name:'旅程'}) RETURN d;
MERGE (d:Domain {name:'项目进展'}) RETURN d;
MERGE (d:Domain {name:'起点'}) RETURN d;
MERGE (d:Domain {name:'方向'}) RETURN d;
MERGE (d:Domain {name:'障碍'}) RETURN d;
MERGE (d:Domain {name:'里程碑'}) RETURN d;
MERGE (d:Domain {name:'停滞'}) RETURN d;
MERGE (m:MetaphorMapping {id:'L1_53d552bc'}) SET m.layer=1, m.source='旅程', m.target='项目进展', m.ground=["起点", "方向", "障碍", "里程碑", "停滞"], m.triggers=["前进"], m.description='旅程→项目进展：把项目进展比作旅程，强调起点、方向、障碍、里程碑、停滞。触发词：前进。', m.confidence=0.6, m.isExtended=false, m.deprecated=false, m.novelty='novel', m.source_type='MOTION', m.cascade_id='C_PROGRESS_JOURNEY', m.frame_id='F_PROG_JOURNEY', m.extractor_version='1.0.0';
MATCH (m:MetaphorMapping {id:'L1_53d552bc'}), (s:Domain {name:'旅程'}) MERGE (m)-[:HAS_SOURCE]->(s);
MATCH (m:MetaphorMapping {id:'L1_53d552bc'}), (t:Domain {name:'项目进展'}) MERGE (m)-[:HAS_TARGET]->(t);
MATCH (m:MetaphorMapping {id:'L1_53d552bc'}), (g:Domain {name:'起点'}) MERGE (m)-[:HAS_GROUND]->(g);
MATCH (m:MetaphorMapping {id:'L1_53d552bc'}), (g:Domain {name:'方向'}) MERGE (m)-[:HAS_GROUND]->(g);
MATCH (m:MetaphorMapping {id:'L1_53d552bc'}), (g:Domain {name:'障碍'}) MERGE (m)-[:HAS_GROUND]->(g);
MATCH (m:MetaphorMapping {id:'L1_53d552bc'}), (g:Domain {name:'里程碑'}) MERGE (m)-[:HAS_GROUND]->(g);
MATCH (m:MetaphorMapping {id:'L1_53d552bc'}), (g:Domain {name:'停滞'}) MERGE (m)-[:HAS_GROUND]->(g);
MERGE (ch:Chunk {id:'demo_doc_c0'}) SET ch.doc_id='demo_doc';
MATCH (m:MetaphorMapping {id:'L1_53d552bc'}), (ch:Chunk {id:'demo_doc_c0'}) MERGE (m)-[:SPANS]->(ch);
MERGE (d:Domain {name:'地形'}) RETURN d;
MERGE (d:Domain {name:'项目困境'}) RETURN d;
MERGE (d:Domain {name:'泥潭'}) RETURN d;
MERGE (d:Domain {name:'深坑'}) RETURN d;
MERGE (d:Domain {name:'陡坡'}) RETURN d;
MERGE (d:Domain {name:'沼泽'}) RETURN d;
MERGE (m:MetaphorMapping {id:'L1_28970c85'}) SET m.layer=1, m.source='地形', m.target='项目困境', m.ground=["泥潭", "深坑", "陡坡", "沼泽"], m.triggers=["泥潭"], m.description='地形→项目困境：把项目困境比作地形，强调泥潭、深坑、陡坡、沼泽。触发词：泥潭。', m.confidence=0.6, m.isExtended=false, m.deprecated=false, m.novelty='novel', m.source_type='NATURAL_PHENOMENON', m.cascade_id='C_PROGRESS_JOURNEY', m.frame_id='F_OBST_TERRAIN', m.extractor_version='1.0.0';
MATCH (m:MetaphorMapping {id:'L1_28970c85'}), (s:Domain {name:'地形'}) MERGE (m)-[:HAS_SOURCE]->(s);
MATCH (m:MetaphorMapping {id:'L1_28970c85'}), (t:Domain {name:'项目困境'}) MERGE (m)-[:HAS_TARGET]->(t);
MATCH (m:MetaphorMapping {id:'L1_28970c85'}), (g:Domain {name:'泥潭'}) MERGE (m)-[:HAS_GROUND]->(g);
MATCH (m:MetaphorMapping {id:'L1_28970c85'}), (g:Domain {name:'深坑'}) MERGE (m)-[:HAS_GROUND]->(g);
MATCH (m:MetaphorMapping {id:'L1_28970c85'}), (g:Domain {name:'陡坡'}) MERGE (m)-[:HAS_GROUND]->(g);
MATCH (m:MetaphorMapping {id:'L1_28970c85'}), (g:Domain {name:'沼泽'}) MERGE (m)-[:HAS_GROUND]->(g);
MERGE (ch:Chunk {id:'demo_doc_c0'}) SET ch.doc_id='demo_doc';
MATCH (m:MetaphorMapping {id:'L1_28970c85'}), (ch:Chunk {id:'demo_doc_c0'}) MERGE (m)-[:SPANS]->(ch);
MERGE (d:Domain {name:'机器'}) RETURN d;
MERGE (d:Domain {name:'生活状态'}) RETURN d;
MERGE (d:Domain {name:'紧绷'}) RETURN d;
MERGE (d:Domain {name:'需要放松'}) RETURN d;
MERGE (d:Domain {name:'机械重复'}) RETURN d;
MERGE (d:Domain {name:'缺乏弹性'}) RETURN d;
MERGE (m:MetaphorMapping {id:'L1_42055406'}) SET m.layer=1, m.source='机器', m.target='生活状态', m.ground=["紧绷", "需要放松", "机械重复", "缺乏弹性"], m.triggers=["发条", "拧紧"], m.description='机器→生活状态：把生活状态比作机器，强调紧绷、需要放松、机械重复、缺乏弹性。触发词：发条、拧紧。', m.confidence=0.8, m.isExtended=false, m.deprecated=false, m.novelty='conventional', m.source_type='MACHINE', m.cascade_id='C_LIFE_MACHINE', m.frame_id='F_LIFE_MACHINE', m.extractor_version='1.0.0';
MATCH (m:MetaphorMapping {id:'L1_42055406'}), (s:Domain {name:'机器'}) MERGE (m)-[:HAS_SOURCE]->(s);
MATCH (m:MetaphorMapping {id:'L1_42055406'}), (t:Domain {name:'生活状态'}) MERGE (m)-[:HAS_TARGET]->(t);
MATCH (m:MetaphorMapping {id:'L1_42055406'}), (g:Domain {name:'紧绷'}) MERGE (m)-[:HAS_GROUND]->(g);
MATCH (m:MetaphorMapping {id:'L1_42055406'}), (g:Domain {name:'需要放松'}) MERGE (m)-[:HAS_GROUND]->(g);
MATCH (m:MetaphorMapping {id:'L1_42055406'}), (g:Domain {name:'机械重复'}) MERGE (m)-[:HAS_GROUND]->(g);
MATCH (m:MetaphorMapping {id:'L1_42055406'}), (g:Domain {name:'缺乏弹性'}) MERGE (m)-[:HAS_GROUND]->(g);
MERGE (ch:Chunk {id:'demo_doc_c1'}) SET ch.doc_id='demo_doc';
MATCH (m:MetaphorMapping {id:'L1_42055406'}), (ch:Chunk {id:'demo_doc_c1'}) MERGE (m)-[:SPANS]->(ch);
MERGE (ch:Chunk {id:'demo_doc_c1'}) SET ch.doc_id='demo_doc';
MATCH (m:MetaphorMapping {id:'L1_42055406'}), (ch:Chunk {id:'demo_doc_c1'}) MERGE (m)-[:SPANS]->(ch);
MERGE (d:Domain {name:'机器'}) RETURN d;
MERGE (d:Domain {name:'生活状态'}) RETURN d;
MERGE (d:Domain {name:'紧绷'}) RETURN d;
MERGE (d:Domain {name:'需要放松'}) RETURN d;
MERGE (d:Domain {name:'机械重复'}) RETURN d;
MERGE (d:Domain {name:'缺乏弹性'}) RETURN d;
MERGE (m:MetaphorMapping {id:'L1_112e7e21'}) SET m.layer=1, m.source='机器', m.target='生活状态', m.ground=["紧绷", "需要放松", "机械重复", "缺乏弹性"], m.triggers=["拧紧", "机械"], m.description='机器→生活状态：把生活状态比作机器，强调紧绷、需要放松、机械重复、缺乏弹性。触发词：拧紧、机械。', m.confidence=0.8, m.isExtended=false, m.deprecated=false, m.novelty='conventional', m.source_type='MACHINE', m.cascade_id='C_LIFE_MACHINE', m.frame_id='F_LIFE_MACHINE', m.extractor_version='1.0.0';
MATCH (m:MetaphorMapping {id:'L1_112e7e21'}), (s:Domain {name:'机器'}) MERGE (m)-[:HAS_SOURCE]->(s);
MATCH (m:MetaphorMapping {id:'L1_112e7e21'}), (t:Domain {name:'生活状态'}) MERGE (m)-[:HAS_TARGET]->(t);
MATCH (m:MetaphorMapping {id:'L1_112e7e21'}), (g:Domain {name:'紧绷'}) MERGE (m)-[:HAS_GROUND]->(g);
MATCH (m:MetaphorMapping {id:'L1_112e7e21'}), (g:Domain {name:'需要放松'}) MERGE (m)-[:HAS_GROUND]->(g);
MATCH (m:MetaphorMapping {id:'L1_112e7e21'}), (g:Domain {name:'机械重复'}) MERGE (m)-[:HAS_GROUND]->(g);
MATCH (m:MetaphorMapping {id:'L1_112e7e21'}), (g:Domain {name:'缺乏弹性'}) MERGE (m)-[:HAS_GROUND]->(g);
MERGE (ch:Chunk {id:'demo_doc_c2'}) SET ch.doc_id='demo_doc';
MATCH (m:MetaphorMapping {id:'L1_112e7e21'}), (ch:Chunk {id:'demo_doc_c2'}) MERGE (m)-[:SPANS]->(ch);
MERGE (ch:Chunk {id:'demo_doc_c2'}) SET ch.doc_id='demo_doc';
MATCH (m:MetaphorMapping {id:'L1_112e7e21'}), (ch:Chunk {id:'demo_doc_c2'}) MERGE (m)-[:SPANS]->(ch);
MERGE (d:Domain {name:'战争'}) RETURN d;
MERGE (d:Domain {name:'商业竞争'}) RETURN d;
MERGE (d:Domain {name:'对手'}) RETURN d;
MERGE (d:Domain {name:'阵地'}) RETURN d;
MERGE (d:Domain {name:'突围'}) RETURN d;
MERGE (d:Domain {name:'卡位'}) RETURN d;
MERGE (m:MetaphorMapping {id:'L1_a759152a'}) SET m.layer=1, m.source='战争', m.target='商业竞争', m.ground=["对手", "阵地", "突围", "卡位"], m.triggers=["商战", "抢滩", "护城河"], m.description='战争→商业竞争：把商业竞争比作战争，强调对手、阵地、突围、卡位。触发词：商战、抢滩、护城河。', m.confidence=1.0, m.isExtended=false, m.deprecated=false, m.novelty='conventional', m.source_type='WAR', m.cascade_id='C_ARG_WAR', m.frame_id='F_COMP_WAR', m.extractor_version='1.0.0';
MATCH (m:MetaphorMapping {id:'L1_a759152a'}), (s:Domain {name:'战争'}) MERGE (m)-[:HAS_SOURCE]->(s);
MATCH (m:MetaphorMapping {id:'L1_a759152a'}), (t:Domain {name:'商业竞争'}) MERGE (m)-[:HAS_TARGET]->(t);
MATCH (m:MetaphorMapping {id:'L1_a759152a'}), (g:Domain {name:'对手'}) MERGE (m)-[:HAS_GROUND]->(g);
MATCH (m:MetaphorMapping {id:'L1_a759152a'}), (g:Domain {name:'阵地'}) MERGE (m)-[:HAS_GROUND]->(g);
MATCH (m:MetaphorMapping {id:'L1_a759152a'}), (g:Domain {name:'突围'}) MERGE (m)-[:HAS_GROUND]->(g);
MATCH (m:MetaphorMapping {id:'L1_a759152a'}), (g:Domain {name:'卡位'}) MERGE (m)-[:HAS_GROUND]->(g);
MERGE (ch:Chunk {id:'demo_doc_c3'}) SET ch.doc_id='demo_doc';
MATCH (m:MetaphorMapping {id:'L1_a759152a'}), (ch:Chunk {id:'demo_doc_c3'}) MERGE (m)-[:SPANS]->(ch);
MERGE (ch:Chunk {id:'demo_doc_c3'}) SET ch.doc_id='demo_doc';
MATCH (m:MetaphorMapping {id:'L1_a759152a'}), (ch:Chunk {id:'demo_doc_c3'}) MERGE (m)-[:SPANS]->(ch);
MERGE (ch:Chunk {id:'demo_doc_c3'}) SET ch.doc_id='demo_doc';
MATCH (m:MetaphorMapping {id:'L1_a759152a'}), (ch:Chunk {id:'demo_doc_c3'}) MERGE (m)-[:SPANS]->(ch);
MERGE (d:Domain {name:'战争'}) RETURN d;
MERGE (d:Domain {name:'争论'}) RETURN d;
MERGE (d:Domain {name:'对抗'}) RETURN d;
MERGE (d:Domain {name:'胜负'}) RETURN d;
MERGE (d:Domain {name:'进攻'}) RETURN d;
MERGE (d:Domain {name:'防守'}) RETURN d;
MERGE (d:Domain {name:'战略'}) RETURN d;
MERGE (m:MetaphorMapping {id:'L1_78ef9ba0'}) SET m.layer=1, m.source='战争', m.target='争论', m.ground=["对抗", "胜负", "进攻", "防守", "战略"], m.triggers=["战壕"], m.description='战争→争论：把争论比作战争，强调对抗、胜负、进攻、防守、战略。触发词：战壕。', m.confidence=0.6, m.isExtended=false, m.deprecated=false, m.novelty='novel', m.source_type='WAR', m.cascade_id='C_ARG_WAR', m.frame_id='F_ARG_WAR', m.extractor_version='1.0.0';
MATCH (m:MetaphorMapping {id:'L1_78ef9ba0'}), (s:Domain {name:'战争'}) MERGE (m)-[:HAS_SOURCE]->(s);
MATCH (m:MetaphorMapping {id:'L1_78ef9ba0'}), (t:Domain {name:'争论'}) MERGE (m)-[:HAS_TARGET]->(t);
MATCH (m:MetaphorMapping {id:'L1_78ef9ba0'}), (g:Domain {name:'对抗'}) MERGE (m)-[:HAS_GROUND]->(g);
MATCH (m:MetaphorMapping {id:'L1_78ef9ba0'}), (g:Domain {name:'胜负'}) MERGE (m)-[:HAS_GROUND]->(g);
MATCH (m:MetaphorMapping {id:'L1_78ef9ba0'}), (g:Domain {name:'进攻'}) MERGE (m)-[:HAS_GROUND]->(g);
MATCH (m:MetaphorMapping {id:'L1_78ef9ba0'}), (g:Domain {name:'防守'}) MERGE (m)-[:HAS_GROUND]->(g);
MATCH (m:MetaphorMapping {id:'L1_78ef9ba0'}), (g:Domain {name:'战略'}) MERGE (m)-[:HAS_GROUND]->(g);
MERGE (ch:Chunk {id:'demo_doc_c3'}) SET ch.doc_id='demo_doc';
MATCH (m:MetaphorMapping {id:'L1_78ef9ba0'}), (ch:Chunk {id:'demo_doc_c3'}) MERGE (m)-[:SPANS]->(ch);
MERGE (d:Domain {name:'热'}) RETURN d;
MERGE (d:Domain {name:'愤怒'}) RETURN d;
MERGE (d:Domain {name:'升温'}) RETURN d;
MERGE (d:Domain {name:'爆发'}) RETURN d;
MERGE (d:Domain {name:'灼烧'}) RETURN d;
MERGE (d:Domain {name:'沸腾'}) RETURN d;
MERGE (m:MetaphorMapping {id:'L1_e91f31b2'}) SET m.layer=1, m.source='热', m.target='愤怒', m.ground=["升温", "爆发", "灼烧", "沸腾"], m.triggers=["怒火", "火大", "爆发"], m.description='热→愤怒：把愤怒比作热，强调升温、爆发、灼烧、沸腾。触发词：怒火、火大、爆发。', m.confidence=1.0, m.isExtended=false, m.deprecated=false, m.novelty='conventional', m.source_type='BODY_SENSATION', m.cascade_id='C_ANGER_HEAT', m.frame_id='F_ANGER_HEAT', m.extractor_version='1.0.0';
MATCH (m:MetaphorMapping {id:'L1_e91f31b2'}), (s:Domain {name:'热'}) MERGE (m)-[:HAS_SOURCE]->(s);
MATCH (m:MetaphorMapping {id:'L1_e91f31b2'}), (t:Domain {name:'愤怒'}) MERGE (m)-[:HAS_TARGET]->(t);
MATCH (m:MetaphorMapping {id:'L1_e91f31b2'}), (g:Domain {name:'升温'}) MERGE (m)-[:HAS_GROUND]->(g);
MATCH (m:MetaphorMapping {id:'L1_e91f31b2'}), (g:Domain {name:'爆发'}) MERGE (m)-[:HAS_GROUND]->(g);
MATCH (m:MetaphorMapping {id:'L1_e91f31b2'}), (g:Domain {name:'灼烧'}) MERGE (m)-[:HAS_GROUND]->(g);
MATCH (m:MetaphorMapping {id:'L1_e91f31b2'}), (g:Domain {name:'沸腾'}) MERGE (m)-[:HAS_GROUND]->(g);
MERGE (ch:Chunk {id:'demo_doc_c5'}) SET ch.doc_id='demo_doc';
MATCH (m:MetaphorMapping {id:'L1_e91f31b2'}), (ch:Chunk {id:'demo_doc_c5'}) MERGE (m)-[:SPANS]->(ch);
MERGE (ch:Chunk {id:'demo_doc_c5'}) SET ch.doc_id='demo_doc';
MATCH (m:MetaphorMapping {id:'L1_e91f31b2'}), (ch:Chunk {id:'demo_doc_c5'}) MERGE (m)-[:SPANS]->(ch);
MERGE (ch:Chunk {id:'demo_doc_c5'}) SET ch.doc_id='demo_doc';
MATCH (m:MetaphorMapping {id:'L1_e91f31b2'}), (ch:Chunk {id:'demo_doc_c5'}) MERGE (m)-[:SPANS]->(ch);
MERGE (d:Domain {name:'容器'}) RETURN d;
MERGE (d:Domain {name:'情绪'}) RETURN d;
MERGE (d:Domain {name:'积压'}) RETURN d;
MERGE (d:Domain {name:'释放'}) RETURN d;
MERGE (d:Domain {name:'压抑'}) RETURN d;
MERGE (d:Domain {name:'满溢'}) RETURN d;
MERGE (m:MetaphorMapping {id:'L1_000c9e5b'}) SET m.layer=1, m.source='容器', m.target='情绪', m.ground=["积压", "释放", "压抑", "满溢"], m.triggers=["积压"], m.description='容器→情绪：把情绪比作容器，强调积压、释放、压抑、满溢。触发词：积压。', m.confidence=0.6, m.isExtended=false, m.deprecated=false, m.novelty='novel', m.source_type='CONTAINER', m.cascade_id='C_MIND_CONTAINER', m.frame_id='F_EMO_CONT', m.extractor_version='1.0.0';
MATCH (m:MetaphorMapping {id:'L1_000c9e5b'}), (s:Domain {name:'容器'}) MERGE (m)-[:HAS_SOURCE]->(s);
MATCH (m:MetaphorMapping {id:'L1_000c9e5b'}), (t:Domain {name:'情绪'}) MERGE (m)-[:HAS_TARGET]->(t);
MATCH (m:MetaphorMapping {id:'L1_000c9e5b'}), (g:Domain {name:'积压'}) MERGE (m)-[:HAS_GROUND]->(g);
MATCH (m:MetaphorMapping {id:'L1_000c9e5b'}), (g:Domain {name:'释放'}) MERGE (m)-[:HAS_GROUND]->(g);
MATCH (m:MetaphorMapping {id:'L1_000c9e5b'}), (g:Domain {name:'压抑'}) MERGE (m)-[:HAS_GROUND]->(g);
MATCH (m:MetaphorMapping {id:'L1_000c9e5b'}), (g:Domain {name:'满溢'}) MERGE (m)-[:HAS_GROUND]->(g);
MERGE (ch:Chunk {id:'demo_doc_c5'}) SET ch.doc_id='demo_doc';
MATCH (m:MetaphorMapping {id:'L1_000c9e5b'}), (ch:Chunk {id:'demo_doc_c5'}) MERGE (m)-[:SPANS]->(ch);
MERGE (d:Domain {name:'容器'}) RETURN d;
MERGE (d:Domain {name:'心智'}) RETURN d;
MERGE (d:Domain {name:'装满'}) RETURN d;
MERGE (d:Domain {name:'溢出'}) RETURN d;
MERGE (d:Domain {name:'封闭'}) RETURN d;
MERGE (d:Domain {name:'空洞'}) RETURN d;
MERGE (m:MetaphorMapping {id:'L1_2bf6759a'}) SET m.layer=1, m.source='容器', m.target='心智', m.ground=["装满", "溢出", "封闭", "空洞"], m.triggers=["溢出", "装满"], m.description='容器→心智：把心智比作容器，强调装满、溢出、封闭、空洞。触发词：溢出、装满。', m.confidence=0.8, m.isExtended=false, m.deprecated=false, m.novelty='conventional', m.source_type='CONTAINER', m.cascade_id='C_MIND_CONTAINER', m.frame_id='F_MIND_CONT', m.extractor_version='1.0.0';
MATCH (m:MetaphorMapping {id:'L1_2bf6759a'}), (s:Domain {name:'容器'}) MERGE (m)-[:HAS_SOURCE]->(s);
MATCH (m:MetaphorMapping {id:'L1_2bf6759a'}), (t:Domain {name:'心智'}) MERGE (m)-[:HAS_TARGET]->(t);
MATCH (m:MetaphorMapping {id:'L1_2bf6759a'}), (g:Domain {name:'装满'}) MERGE (m)-[:HAS_GROUND]->(g);
MATCH (m:MetaphorMapping {id:'L1_2bf6759a'}), (g:Domain {name:'溢出'}) MERGE (m)-[:HAS_GROUND]->(g);
MATCH (m:MetaphorMapping {id:'L1_2bf6759a'}), (g:Domain {name:'封闭'}) MERGE (m)-[:HAS_GROUND]->(g);
MATCH (m:MetaphorMapping {id:'L1_2bf6759a'}), (g:Domain {name:'空洞'}) MERGE (m)-[:HAS_GROUND]->(g);
MERGE (ch:Chunk {id:'demo_doc_c6'}) SET ch.doc_id='demo_doc';
MATCH (m:MetaphorMapping {id:'L1_2bf6759a'}), (ch:Chunk {id:'demo_doc_c6'}) MERGE (m)-[:SPANS]->(ch);
MERGE (ch:Chunk {id:'demo_doc_c6'}) SET ch.doc_id='demo_doc';
MATCH (m:MetaphorMapping {id:'L1_2bf6759a'}), (ch:Chunk {id:'demo_doc_c6'}) MERGE (m)-[:SPANS]->(ch);
MERGE (d:Domain {name:'容器'}) RETURN d;
MERGE (d:Domain {name:'情绪'}) RETURN d;
MERGE (d:Domain {name:'积压'}) RETURN d;
MERGE (d:Domain {name:'释放'}) RETURN d;
MERGE (d:Domain {name:'压抑'}) RETURN d;
MERGE (d:Domain {name:'满溢'}) RETURN d;
MERGE (m:MetaphorMapping {id:'L1_a0555b1d'}) SET m.layer=1, m.source='容器', m.target='情绪', m.ground=["积压", "释放", "压抑", "满溢"], m.triggers=["满溢", "装不下"], m.description='容器→情绪：把情绪比作容器，强调积压、释放、压抑、满溢。触发词：满溢、装不下。', m.confidence=0.8, m.isExtended=false, m.deprecated=false, m.novelty='conventional', m.source_type='CONTAINER', m.cascade_id='C_MIND_CONTAINER', m.frame_id='F_EMO_CONT', m.extractor_version='1.0.0';
MATCH (m:MetaphorMapping {id:'L1_a0555b1d'}), (s:Domain {name:'容器'}) MERGE (m)-[:HAS_SOURCE]->(s);
MATCH (m:MetaphorMapping {id:'L1_a0555b1d'}), (t:Domain {name:'情绪'}) MERGE (m)-[:HAS_TARGET]->(t);
MATCH (m:MetaphorMapping {id:'L1_a0555b1d'}), (g:Domain {name:'积压'}) MERGE (m)-[:HAS_GROUND]->(g);
MATCH (m:MetaphorMapping {id:'L1_a0555b1d'}), (g:Domain {name:'释放'}) MERGE (m)-[:HAS_GROUND]->(g);
MATCH (m:MetaphorMapping {id:'L1_a0555b1d'}), (g:Domain {name:'压抑'}) MERGE (m)-[:HAS_GROUND]->(g);
MATCH (m:MetaphorMapping {id:'L1_a0555b1d'}), (g:Domain {name:'满溢'}) MERGE (m)-[:HAS_GROUND]->(g);
MERGE (ch:Chunk {id:'demo_doc_c6'}) SET ch.doc_id='demo_doc';
MATCH (m:MetaphorMapping {id:'L1_a0555b1d'}), (ch:Chunk {id:'demo_doc_c6'}) MERGE (m)-[:SPANS]->(ch);
MERGE (ch:Chunk {id:'demo_doc_c6'}) SET ch.doc_id='demo_doc';
MATCH (m:MetaphorMapping {id:'L1_a0555b1d'}), (ch:Chunk {id:'demo_doc_c6'}) MERGE (m)-[:SPANS]->(ch);
MERGE (d:Domain {name:'机器'}) RETURN d;
MERGE (d:Domain {name:'生活状态'}) RETURN d;
MERGE (d:Domain {name:'机械重复'}) RETURN d;
MERGE (d:Domain {name:'紧绷'}) RETURN d;
MERGE (d:Domain {name:'缺乏弹性'}) RETURN d;
MERGE (d:Domain {name:'需要放松'}) RETURN d;
MERGE (m:MetaphorMapping {id:'EXT_4522711d'}) SET m.layer=1.5, m.source='机器', m.target='生活状态', m.ground=["机械重复", "紧绷", "缺乏弹性", "需要放松"], m.triggers=["发条", "拧紧", "机械"], m.description='机器→生活状态：把生活状态比作机器，强调机械重复、紧绷、缺乏弹性、需要放松。触发词：发条、拧紧、机械。', m.confidence=0.8, m.isExtended=true, m.deprecated=false, m.novelty='conventional', m.source_type='MACHINE', m.cascade_id='C_LIFE_MACHINE', m.frame_id='F_LIFE_MACHINE', m.extractor_version='1.0.0';
MATCH (m:MetaphorMapping {id:'EXT_4522711d'}), (s:Domain {name:'机器'}) MERGE (m)-[:HAS_SOURCE]->(s);
MATCH (m:MetaphorMapping {id:'EXT_4522711d'}), (t:Domain {name:'生活状态'}) MERGE (m)-[:HAS_TARGET]->(t);
MATCH (m:MetaphorMapping {id:'EXT_4522711d'}), (g:Domain {name:'机械重复'}) MERGE (m)-[:HAS_GROUND]->(g);
MATCH (m:MetaphorMapping {id:'EXT_4522711d'}), (g:Domain {name:'紧绷'}) MERGE (m)-[:HAS_GROUND]->(g);
MATCH (m:MetaphorMapping {id:'EXT_4522711d'}), (g:Domain {name:'缺乏弹性'}) MERGE (m)-[:HAS_GROUND]->(g);
MATCH (m:MetaphorMapping {id:'EXT_4522711d'}), (g:Domain {name:'需要放松'}) MERGE (m)-[:HAS_GROUND]->(g);
MERGE (ch:Chunk {id:'demo_doc_c1'}) SET ch.doc_id='demo_doc';
MATCH (m:MetaphorMapping {id:'EXT_4522711d'}), (ch:Chunk {id:'demo_doc_c1'}) MERGE (m)-[:SPANS]->(ch);
MERGE (ch:Chunk {id:'demo_doc_c1'}) SET ch.doc_id='demo_doc';
MATCH (m:MetaphorMapping {id:'EXT_4522711d'}), (ch:Chunk {id:'demo_doc_c1'}) MERGE (m)-[:SPANS]->(ch);
MERGE (ch:Chunk {id:'demo_doc_c2'}) SET ch.doc_id='demo_doc';
MATCH (m:MetaphorMapping {id:'EXT_4522711d'}), (ch:Chunk {id:'demo_doc_c2'}) MERGE (m)-[:SPANS]->(ch);
MERGE (ch:Chunk {id:'demo_doc_c2'}) SET ch.doc_id='demo_doc';
MATCH (m:MetaphorMapping {id:'EXT_4522711d'}), (ch:Chunk {id:'demo_doc_c2'}) MERGE (m)-[:SPANS]->(ch);
MERGE (d:Domain {name:'容器'}) RETURN d;
MERGE (d:Domain {name:'情绪'}) RETURN d;
MERGE (d:Domain {name:'压抑'}) RETURN d;
MERGE (d:Domain {name:'满溢'}) RETURN d;
MERGE (d:Domain {name:'积压'}) RETURN d;
MERGE (d:Domain {name:'释放'}) RETURN d;
MERGE (m:MetaphorMapping {id:'EXT_ee9fbfc4'}) SET m.layer=1.5, m.source='容器', m.target='情绪', m.ground=["压抑", "满溢", "积压", "释放"], m.triggers=["满溢", "积压", "装不下"], m.description='容器→情绪：把情绪比作容器，强调压抑、满溢、积压、释放。触发词：满溢、积压、装不下。', m.confidence=0.8, m.isExtended=true, m.deprecated=false, m.novelty='novel', m.source_type='CONTAINER', m.cascade_id='C_MIND_CONTAINER', m.frame_id='F_EMO_CONT', m.extractor_version='1.0.0';
MATCH (m:MetaphorMapping {id:'EXT_ee9fbfc4'}), (s:Domain {name:'容器'}) MERGE (m)-[:HAS_SOURCE]->(s);
MATCH (m:MetaphorMapping {id:'EXT_ee9fbfc4'}), (t:Domain {name:'情绪'}) MERGE (m)-[:HAS_TARGET]->(t);
MATCH (m:MetaphorMapping {id:'EXT_ee9fbfc4'}), (g:Domain {name:'压抑'}) MERGE (m)-[:HAS_GROUND]->(g);
MATCH (m:MetaphorMapping {id:'EXT_ee9fbfc4'}), (g:Domain {name:'满溢'}) MERGE (m)-[:HAS_GROUND]->(g);
MATCH (m:MetaphorMapping {id:'EXT_ee9fbfc4'}), (g:Domain {name:'积压'}) MERGE (m)-[:HAS_GROUND]->(g);
MATCH (m:MetaphorMapping {id:'EXT_ee9fbfc4'}), (g:Domain {name:'释放'}) MERGE (m)-[:HAS_GROUND]->(g);
MERGE (ch:Chunk {id:'demo_doc_c5'}) SET ch.doc_id='demo_doc';
MATCH (m:MetaphorMapping {id:'EXT_ee9fbfc4'}), (ch:Chunk {id:'demo_doc_c5'}) MERGE (m)-[:SPANS]->(ch);
MERGE (ch:Chunk {id:'demo_doc_c6'}) SET ch.doc_id='demo_doc';
MATCH (m:MetaphorMapping {id:'EXT_ee9fbfc4'}), (ch:Chunk {id:'demo_doc_c6'}) MERGE (m)-[:SPANS]->(ch);
MERGE (ch:Chunk {id:'demo_doc_c6'}) SET ch.doc_id='demo_doc';
MATCH (m:MetaphorMapping {id:'EXT_ee9fbfc4'}), (ch:Chunk {id:'demo_doc_c6'}) MERGE (m)-[:SPANS]->(ch);
MERGE (f:MetaphorFrame {id:'F_PROG_JOURNEY'}) SET f.name='PROGRESS_IS_JOURNEY', f.layer=2, f.source_frame='Path', f.target_frame='Project';
MATCH (f:MetaphorFrame {id:'F_PROG_JOURNEY'}), (m:MetaphorMapping {id:'L1_53d552bc'}) MERGE (m)-[:IN_FRAME]->(f);
MERGE (f:MetaphorFrame {id:'F_OBST_TERRAIN'}) SET f.name='OBSTACLE_IS_TERRAIN', f.layer=2, f.source_frame='Terrain', f.target_frame='Difficulty';
MATCH (f:MetaphorFrame {id:'F_OBST_TERRAIN'}), (m:MetaphorMapping {id:'L1_28970c85'}) MERGE (m)-[:IN_FRAME]->(f);
MERGE (f:MetaphorFrame {id:'F_LIFE_MACHINE'}) SET f.name='LIFE_IS_A_MACHINE', f.layer=2, f.source_frame='Machine', f.target_frame='Life';
MATCH (f:MetaphorFrame {id:'F_LIFE_MACHINE'}), (m:MetaphorMapping {id:'L1_42055406'}) MERGE (m)-[:IN_FRAME]->(f);
MATCH (f:MetaphorFrame {id:'F_LIFE_MACHINE'}), (m:MetaphorMapping {id:'L1_112e7e21'}) MERGE (m)-[:IN_FRAME]->(f);
MATCH (f:MetaphorFrame {id:'F_LIFE_MACHINE'}), (m:MetaphorMapping {id:'EXT_4522711d'}) MERGE (m)-[:IN_FRAME]->(f);
MERGE (f:MetaphorFrame {id:'F_COMP_WAR'}) SET f.name='COMPETITION_IS_WAR', f.layer=2, f.source_frame='Combat', f.target_frame='Business';
MATCH (f:MetaphorFrame {id:'F_COMP_WAR'}), (m:MetaphorMapping {id:'L1_a759152a'}) MERGE (m)-[:IN_FRAME]->(f);
MERGE (f:MetaphorFrame {id:'F_ARG_WAR'}) SET f.name='ARGUMENT_IS_WAR', f.layer=2, f.source_frame='Combat', f.target_frame='Communication';
MATCH (f:MetaphorFrame {id:'F_ARG_WAR'}), (m:MetaphorMapping {id:'L1_78ef9ba0'}) MERGE (m)-[:IN_FRAME]->(f);
MERGE (f:MetaphorFrame {id:'F_ANGER_HEAT'}) SET f.name='ANGER_IS_HEAT', f.layer=2, f.source_frame='Heat', f.target_frame='Emotion';
MATCH (f:MetaphorFrame {id:'F_ANGER_HEAT'}), (m:MetaphorMapping {id:'L1_e91f31b2'}) MERGE (m)-[:IN_FRAME]->(f);
MERGE (f:MetaphorFrame {id:'F_EMO_CONT'}) SET f.name='EMOTION_IS_CONTAINER', f.layer=2, f.source_frame='Container', f.target_frame='Emotion';
MATCH (f:MetaphorFrame {id:'F_EMO_CONT'}), (m:MetaphorMapping {id:'L1_000c9e5b'}) MERGE (m)-[:IN_FRAME]->(f);
MATCH (f:MetaphorFrame {id:'F_EMO_CONT'}), (m:MetaphorMapping {id:'L1_a0555b1d'}) MERGE (m)-[:IN_FRAME]->(f);
MATCH (f:MetaphorFrame {id:'F_EMO_CONT'}), (m:MetaphorMapping {id:'EXT_ee9fbfc4'}) MERGE (m)-[:IN_FRAME]->(f);
MERGE (f:MetaphorFrame {id:'F_MIND_CONT'}) SET f.name='MIND_IS_CONTAINER', f.layer=2, f.source_frame='Container', f.target_frame='Mind';
MATCH (f:MetaphorFrame {id:'F_MIND_CONT'}), (m:MetaphorMapping {id:'L1_2bf6759a'}) MERGE (m)-[:IN_FRAME]->(f);
MERGE (c:MetaphorCascade {id:'C_PROGRESS_JOURNEY'}) SET c.name='PROGRESS_IS_JOURNEY', c.layer=3, c.discourse=["项目管理", "政策"], c.typical_triggers=["推进", "转向", "停滞"];
MATCH (c:MetaphorCascade {id:'C_PROGRESS_JOURNEY'}), (f:MetaphorFrame {id:'F_PROG_JOURNEY'}) MERGE (f)-[:IN_CASCADE]->(c);
MATCH (c:MetaphorCascade {id:'C_PROGRESS_JOURNEY'}), (f:MetaphorFrame {id:'F_OBST_TERRAIN'}) MERGE (f)-[:IN_CASCADE]->(c);
MERGE (c:MetaphorCascade {id:'C_LIFE_MACHINE'}) SET c.name='LIFE_IS_A_MACHINE', c.layer=3, c.discourse=["生活", "健康"], c.typical_triggers=["发条", "机械", "磨损"];
MATCH (c:MetaphorCascade {id:'C_LIFE_MACHINE'}), (f:MetaphorFrame {id:'F_LIFE_MACHINE'}) MERGE (f)-[:IN_CASCADE]->(c);
MERGE (c:MetaphorCascade {id:'C_ARG_WAR'}) SET c.name='ARGUMENT_IS_WAR', c.layer=3, c.discourse=["政治评论", "商业竞争"], c.typical_triggers=["开火", "商战", "护城河", "攻城略地"];
MATCH (c:MetaphorCascade {id:'C_ARG_WAR'}), (f:MetaphorFrame {id:'F_COMP_WAR'}) MERGE (f)-[:IN_CASCADE]->(c);
MATCH (c:MetaphorCascade {id:'C_ARG_WAR'}), (f:MetaphorFrame {id:'F_ARG_WAR'}) MERGE (f)-[:IN_CASCADE]->(c);
MERGE (c:MetaphorCascade {id:'C_ANGER_HEAT'}) SET c.name='ANGER_IS_HEAT', c.layer=3, c.discourse=["情绪", "文学"], c.typical_triggers=["火大", "暖心", "沸腾"];
MATCH (c:MetaphorCascade {id:'C_ANGER_HEAT'}), (f:MetaphorFrame {id:'F_ANGER_HEAT'}) MERGE (f)-[:IN_CASCADE]->(c);
MERGE (c:MetaphorCascade {id:'C_MIND_CONTAINER'}) SET c.name='MIND_IS_CONTAINER', c.layer=3, c.discourse=["心理", "文学"], c.typical_triggers=["装满", "积压", "释放"];
MATCH (c:MetaphorCascade {id:'C_MIND_CONTAINER'}), (f:MetaphorFrame {id:'F_EMO_CONT'}) MERGE (f)-[:IN_CASCADE]->(c);
MATCH (c:MetaphorCascade {id:'C_MIND_CONTAINER'}), (f:MetaphorFrame {id:'F_MIND_CONT'}) MERGE (f)-[:IN_CASCADE]->(c);